### ISSUE TITLE
Pontos levantado

### ISSUE THREAD

**Issue by honjoya** [pedroparronchi/pet-finder#1]
Boa tarde @pedroparronchi, abaixo fiz algumas anotações de pontos positivos e negativos, conforme avaliação:

**Pontos a serem melhorados**
- Erro 500 (Erro 500 é um erro bem genérico), caso for validar algo especifico utilizar Exception e code para demonstrar o erro.
- Não é necessário criar uma collection para retornar o paginate, o mesmo já é estruturando.
- Poderia ter utilizado services, command bus e handlers (Aplicando o conceito de SOLID)
- Testes foram implementado testado cenários bem limitados
- Seeds não encontrado "UserSeeder"
- Remover a pasta compactada na raiz do projeto
- Não utilizando nenhuma metodologia de CSS (Poderia ter organizado melhor)

**Pontos positvos**
- Utilizou os relacionamentos da model de maneira correta
- Criou migrate
- Aplicou bem a integração entre API e Frontend (Cors)
- Html, CSS e ReactJS
- Utilizou validação (FormRequest)
- Utilizou a versão no nova do Framework
- Utilizou APIs novas do ReactJS e fez uso de Flexbox e Grid

**Comment by pedroparronchi** [comment]
Dois desses pontos que você mencionou eu nunca utilizei ainda, os demais eu tenho conhecimento prévio e aplico sempre que possível

Sendo os que não nunca apliquei:

- Command bus 
-  Metodologia de CSS

Os demais eu não implementei porque acabei utilizando pouco tempo para o projeto (deixei o tempo total no readme)
